/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PlaceholderItem } from "./components/search-placeholders/search-placeholders";
export { PlaceholderItem } from "./components/search-placeholders/search-placeholders";
export namespace Components {
    interface AppRoot {
    }
    interface LumenSearch {
        "apiEndpoint": string;
        "apiKey": string;
        "displayMode": 'icon' | 'embedded';
        "siteId": string;
        "topK": number;
    }
    interface SearchPlaceholders {
        "customStyles": any;
        "isVisible": boolean;
        "placeholders": PlaceholderItem[];
        "selectPlaceholder": (subtitle: string) => void;
    }
    interface SearchResult {
        "resultId": string;
        "resultSnippet": string;
        "resultTitle": string;
        "resultUrl": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLumenSearchElement extends Components.LumenSearch, HTMLStencilElement {
    }
    var HTMLLumenSearchElement: {
        prototype: HTMLLumenSearchElement;
        new (): HTMLLumenSearchElement;
    };
    interface HTMLSearchPlaceholdersElement extends Components.SearchPlaceholders, HTMLStencilElement {
    }
    var HTMLSearchPlaceholdersElement: {
        prototype: HTMLSearchPlaceholdersElement;
        new (): HTMLSearchPlaceholdersElement;
    };
    interface HTMLSearchResultElement extends Components.SearchResult, HTMLStencilElement {
    }
    var HTMLSearchResultElement: {
        prototype: HTMLSearchResultElement;
        new (): HTMLSearchResultElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "lumen-search": HTMLLumenSearchElement;
        "search-placeholders": HTMLSearchPlaceholdersElement;
        "search-result": HTMLSearchResultElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LumenSearch {
        "apiEndpoint"?: string;
        "apiKey"?: string;
        "displayMode"?: 'icon' | 'embedded';
        "siteId"?: string;
        "topK"?: number;
    }
    interface SearchPlaceholders {
        "customStyles"?: any;
        "isVisible"?: boolean;
        "placeholders"?: PlaceholderItem[];
        "selectPlaceholder"?: (subtitle: string) => void;
    }
    interface SearchResult {
        "resultId"?: string;
        "resultSnippet"?: string;
        "resultTitle"?: string;
        "resultUrl"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "lumen-search": LumenSearch;
        "search-placeholders": SearchPlaceholders;
        "search-result": SearchResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "lumen-search": LocalJSX.LumenSearch & JSXBase.HTMLAttributes<HTMLLumenSearchElement>;
            "search-placeholders": LocalJSX.SearchPlaceholders & JSXBase.HTMLAttributes<HTMLSearchPlaceholdersElement>;
            "search-result": LocalJSX.SearchResult & JSXBase.HTMLAttributes<HTMLSearchResultElement>;
        }
    }
}
