/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CulturehackSearch {
    }
    interface SearchPlaceholders {
        "isVisible": boolean;
    }
    interface SearchResult {
        "resultId": string;
        "resultSnippet": string;
        "resultTitle": string;
        "resultUrl": string;
    }
}
export interface SearchPlaceholdersCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchPlaceholdersElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCulturehackSearchElement extends Components.CulturehackSearch, HTMLStencilElement {
    }
    var HTMLCulturehackSearchElement: {
        prototype: HTMLCulturehackSearchElement;
        new (): HTMLCulturehackSearchElement;
    };
    interface HTMLSearchPlaceholdersElementEventMap {
        "placeholderSelected": string;
    }
    interface HTMLSearchPlaceholdersElement extends Components.SearchPlaceholders, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchPlaceholdersElementEventMap>(type: K, listener: (this: HTMLSearchPlaceholdersElement, ev: SearchPlaceholdersCustomEvent<HTMLSearchPlaceholdersElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchPlaceholdersElementEventMap>(type: K, listener: (this: HTMLSearchPlaceholdersElement, ev: SearchPlaceholdersCustomEvent<HTMLSearchPlaceholdersElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchPlaceholdersElement: {
        prototype: HTMLSearchPlaceholdersElement;
        new (): HTMLSearchPlaceholdersElement;
    };
    interface HTMLSearchResultElement extends Components.SearchResult, HTMLStencilElement {
    }
    var HTMLSearchResultElement: {
        prototype: HTMLSearchResultElement;
        new (): HTMLSearchResultElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "culturehack-search": HTMLCulturehackSearchElement;
        "search-placeholders": HTMLSearchPlaceholdersElement;
        "search-result": HTMLSearchResultElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CulturehackSearch {
    }
    interface SearchPlaceholders {
        "isVisible"?: boolean;
        "onPlaceholderSelected"?: (event: SearchPlaceholdersCustomEvent<string>) => void;
    }
    interface SearchResult {
        "resultId"?: string;
        "resultSnippet"?: string;
        "resultTitle"?: string;
        "resultUrl"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "culturehack-search": CulturehackSearch;
        "search-placeholders": SearchPlaceholders;
        "search-result": SearchResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "culturehack-search": LocalJSX.CulturehackSearch & JSXBase.HTMLAttributes<HTMLCulturehackSearchElement>;
            "search-placeholders": LocalJSX.SearchPlaceholders & JSXBase.HTMLAttributes<HTMLSearchPlaceholdersElement>;
            "search-result": LocalJSX.SearchResult & JSXBase.HTMLAttributes<HTMLSearchResultElement>;
        }
    }
}
