/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface SearchBar {
    }
    interface SearchResult {
        "handleClick"?: () => void;
        "resultId": string;
        "resultSnippet": string;
        "resultTitle": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLSearchResultElement extends Components.SearchResult, HTMLStencilElement {
    }
    var HTMLSearchResultElement: {
        prototype: HTMLSearchResultElement;
        new (): HTMLSearchResultElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "search-bar": HTMLSearchBarElement;
        "search-result": HTMLSearchResultElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface SearchBar {
    }
    interface SearchResult {
        "handleClick"?: () => void;
        "resultId"?: string;
        "resultSnippet"?: string;
        "resultTitle"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "search-bar": SearchBar;
        "search-result": SearchResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "search-bar": LocalJSX.SearchBar & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
            "search-result": LocalJSX.SearchResult & JSXBase.HTMLAttributes<HTMLSearchResultElement>;
        }
    }
}
